version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_PORT: '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend

  web:
    build: .
    
    command: python mysite/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/mysite/
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - backend
   
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      DB_PORT: ${DB_PORT}


    
networks:
  backend:



volumes:
  postgres_data: