# Generated by Django 3.2.7 on 2023-12-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20231203_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
